apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets
spec:
  containers:
    - name: nginx-secrets-pod
      image: nginx
      command: ["env"]
      env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbuser
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbpassword
