apiVersion: v1
kind: Pod
metadata:
        name: nginx-configmap
spec:
  containers:
    - image: nginx
      name: nginx-configmap
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: OWNER
          valueFrom:
            configMapKeyRef:
              name: mycm
              key: owner


