apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - image: nginx
      name: nginx-secrets
      env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbuser
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dppassword

